server:
  port: 8080    #端口号
spring:
  datasource:
    password: WWgct20040925*
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    url: jdbc:mysql://192.168.6.110:3306/redis7?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  data:
    redis:
      host: 192.168.6.110
      port: 6379
      password: wwgct20040925
      database: 0
      jedis:
        pool:
          max-wait: -1ms
          min-idle: 0
          max-idle: 8
          max-active: 8
