server:
  port: 8200    #端口号
spring:
  datasource:
    password: WWgct20040925*
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    url: jdbc:mysql://192.168.6.110:3306/shopping?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
  #allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  #serverTimezone=GMT%2B8&useUnicode=true
  data:
    redis:
      host: 192.168.6.110
      port: 6379
      password: wwgct20040925
      database: 0
      jedis:
        pool:
          max-wait: -1ms
          min-idle: 0
          max-idle: 8
          max-active: 8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #控制台输出sql语句
  global-config:
    db-config:
      logic-delete-value: isDeleted   #全局逻辑删除的实体字段名
      id-type: auto     #配置主键策略
shopping:
  minio:
    endpointUrl: http://192.168.6.110:9001
    username: root
    password: wwgct20040925
    bucketName: shopping-minio
